version: '3.8'

services:
  etl-python:
    build: .
    container_name: clima-etl
    volumes:
      - .:/app
      - ../data:/app/data
      # Montar las credenciales de Copernicus
      - ~/.cdsapirc:/root/.cdsapirc:ro
      - ~/.adsapirc:/root/.adsapirc:ro
    environment:
      - PYTHONUNBUFFERED=1
    # Mantener el contenedor vivo para poder ejecutar scripts
    command: tail -f /dev/null
